### ISSUE TITLE
Installer macro appears to create the ini files wrong.

### ISSUE THREAD

**Issue by Sivivatu** [AdRiley/ChaosReignsWithin-Alteryx-Macros#13]
When running the installer with the latest macro pack it appears to break the folder locations. 

What app looks to be happening is an extra \ is being added in (see attached

[CReW sample.txt](https://github.com/AdRiley/ChaosReignsWithin-Alteryx-Macros/files/329841/CReW.sample.txt)
[CReW.txt](https://github.com/AdRiley/ChaosReignsWithin-Alteryx-Macros/files/329840/CReW.txt)

**Comment by AdRiley** [comment]
Thanks for reporting.  Fixed it.
