### ISSUE TITLE
Runner Macro breaking when run from UNC Location

### ISSUE THREAD

**Issue by Sivivatu** [AdRiley/ChaosReignsWithin-Alteryx-Macros#14]
I'm helping out a client who is using the runner macros from a UNC path location. The macro is breaking and appearing as a black box as below. Im not sure if this is related to the previously closed issue #6 

![image](https://cloud.githubusercontent.com/assets/7496456/23557643/91734888-0028-11e7-92db-1393abec33ac.png)

**Comment by AdRiley** [comment]
Have you checked
that "C:\ProgramData\Alteryx\DataProducts\AddOnData\Macros\CReW.ini" is
pointing at the UNC path?

**Comment by 0ander03** [comment]
Hello,

The path above is pointing at this UNC path D:\Macros\Crew Macros\Macros

The D: also has the UNC path of D:\Scheduled\Modules\Data Quality\Update Course SID.yxmd

Kind regards,

Ryan

**Comment by AdRiley** [comment]
Try changing that D:\ in the ini file to \\bi-dw-prep\

**Comment by 0ander03** [comment]
It cannot pick up the valid entry point on the server now.

![image](https://cloud.githubusercontent.com/assets/26141831/23558958/7933db8e-002d-11e7-897f-a94fde1a89e4.png)

It appears that the D: is not recognised as bi-dw-prep as when pasting the path \\bi-dw-prep\Scheduled\Modules\Data Quality\Update Course SID nothing gets picked up.

**Comment by AdRiley** [comment]
The issues isn't with the Modules path though.  Alteryx can't find the
macros: which is why it displays the black box.

Could you try installing the macros on the server?

**Comment by 0ander03** [comment]
That is very strange, the Crew Macros seems to have been deleted but the Test Macros are still there 

![image](https://cloud.githubusercontent.com/assets/26141831/23559440/ed127686-002e-11e7-9ce2-f2d634e5718f.png)

I have now downloaded them again now and for some reason when opening on my local machine through the mapped drive, it appears that the Crew Macros have been removed again. When trying to install them again locally, I get the following error?

![image](https://cloud.githubusercontent.com/assets/26141831/23559994/c0486b68-0030-11e7-8bf0-38fb62f2690a.png)

How to I gain permissions to then download the Macros?

**Comment by AdRiley** [comment]
Looks like you don't have write permissions to those locations?  Do you
have restricted rights on that machine?  Do you have an IT department who
would be able to give you write permission?

**Comment by 0ander03** [comment]
I have moved the installation configuration settings into a new location and this has now worked perfectly. 
![image](https://cloud.githubusercontent.com/assets/26141831/23602179/0a1c2b86-0247-11e7-8d81-27b6d04438d3.png)
Thank you for your help with this issue.
