### ISSUE TITLE
Alteryx Opening Error

### ISSUE THREAD

**Issue by Sivivatu** [AdRiley/ChaosReignsWithin-Alteryx-Macros#8]
Since installing the CReW macros everytime I open Alteryx I get the error: There was an error loading a macro: Index was outsidce the bounds of the array.

![crew macro opening error](https://cloud.githubusercontent.com/assets/7496456/9872098/03f44b36-5b8f-11e5-83e7-0a771b0eb93f.jpg)

**Comment by AdRiley** [comment]
That's a strange one...  The error message is coming from Alteryx.  I'll have to look at the source to see what might cause it.  What version of Alteryx?  I'm guessing it is something to do with the macro set up on your machine as no one else has reported it.  Might need to do a screen share to take a look.

**Comment by Sivivatu** [comment]
It is a bit weird. Shame we didn't get to look at it during the Alteryx Roadshow. Let me know if this time would https://sunrise.am/m/f2ziffYf12

**Comment by AdRiley** [comment]
This is an Alteryx issue when the CReW macros are trying to be loaded twice by the GUI.  I will file a defect.
